language: node_js

node_js:
  - 14.5.0
  - 10

script:
  - npm run test:ci

branches:
  only:
    - master
    - /v\d+\.\d+.+/

deploy:
  provider: npm
  email: "talk@selwyn.cc"
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true

notifications:
  email: false
